This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./memoria_tfg.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file memoria_tfg.acn....done (47 entries accepted, 0 rejected).
Sorting entries....done (260 comparisons).
Generating output file memoria_tfg.acr....done (71 lines written, 0 warnings).
Output written in memoria_tfg.acr.
Transcript written in memoria_tfg.alg.
